apiVersion: apps/v1
kind: Deployment
metadata:
  name: malaria-app-deployment
  labels:
    app: malaria-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: malaria-app-pod
      app: malaria-app
  template:
    metadata:
      name: malaria-app-pod
      labels:
        name: malaria-app-pod
        app: malaria-app

    spec:
      containers:
      - name: voting-app
        image: vk1025/myapp:malaria_app_3
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: malaria-service
  labels:
    name: malaria-service
    app: malaria-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    name: malaria-app-pod
    app: malaria-app
